### ISSUE TITLE
Completely new dashboard experience

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/low-no-code#98]
### Description
We have to revamp and modernize the existing dashboard interface with a fresh design and enhanced functionality.

Users would like to see essential information easier.

### Impact
This update will improve user engagement, streamline navigation, and provide a more intuitive user experience.

---

## Tasks

- [ ] Search for the best references
- [ ] Create a prototype for the idea
- [ ] New dropdown icon for cards
- [ ] New cards style

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>
